main: me.playbosswar.timeblocks.Main
name: "${project.name}"
author: PlayBossWar
version: "${project.version}"
description: "${project.description}"
api-version: 1.13
commands:
  timeblocks:
    usage: /<command>
    description: Main command
    aliases: [tb]